apiVersion: batch/v1
kind: Job
metadata:
  name: letsencrypt
  labels:
    app: letsencrypt
spec:
  template:
    metadata:
      name: letsencrypt
      labels:
        app: letsencrypt
    spec:
      serviceAccountName: letsencrypt
      containers:
      - image: phanikumary1995/wild-ssl-route-53
        name: letsencrypt
        imagePullPolicy: Always
        env:
        - name: DOMAIN
          value: "*.example.com"
        - name: EMAIL
          value: exmaple@mail.com
        - name: SECRET
          value: example-com-cert
        - name: AWS_ACCESS_KEY_ID
          value: XXXXXXXXXX
        - name: AWS_SECRET_ACCESS_KEY
          value: XXXXXXXXXXXXXXXXXXXXX
      restartPolicy: Never
